name: Deploy to Pages

# Triggers the workflow on pushes to the "main" branch
on:
  push:
    branches: [ "main" ]

# Grants necessary permissions for deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # 1. Checkout repository code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Set up Node.js environment
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # 3. Install dependencies
      - name: Install Dependencies
        run: npm ci

      # 4. Build the project (creates the 'dist' folder)
      - name: Build Project
        run: npm run build

      # 5. Upload the build artifact (the 'dist' folder)
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # The path to your compiled site assets
          path: 'dist' 

      # 6. Deploy the artifact to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4