name: Deploy Vite to Pages

# Triggers the workflow on pushes to the "main" branch
on:
  push:
    branches: [main]

# Grants necessary permissions for deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Ensures only one deployment runs at a time and cancels previous runs
concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repository code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Set up Node.js environment
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # 3. Install dependencies
      - name: Install Dependencies
        run: npm ci

      # 4. Build the project
      - name: Build Project
        run: npm run build

      # 5. Upload the build artifact (the 'dist' folder)
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # The path to your compiled site assets (e.g., Vite output)
          path: dist

  deploy:
    # This job waits for the 'build' job to finish
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # 1. Configure the GitHub Pages deployment environment
      - name: Setup Pages Configuration
        uses: actions/configure-pages@v5

      # 2. Deploy the uploaded artifact to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
